# Generated by Django 4.2.14 on 2024-07-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.CharField(max_length=120),
        ),
    ]
